@include('Admin.layouts.head')
@include('Admin.layouts.header')
@include('Admin.layouts.sidebar')
@include('Admin.layouts.footer')

@yield('head')
@yield('header')
@yield('sidebar')
@yield('main_content')
@yield('footer')